### ISSUE TITLE
Mobile responsive tables is broken

### ISSUE THREAD

**Issue by carxl** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#291]
Hi,

I was checking the new version in mobile view, and found this:

<img width="746" alt="screenshot 2017-10-31 12 18 36" src="https://user-images.githubusercontent.com/2106601/32238761-b322016e-be36-11e7-84b2-b542ba48c1af.png">

Do u know how can solve this?

Thanks.

**Comment by xidedix** [comment]
Just add class `table-responsive` to `<table>` by now. 
The issue will be fixed in the next release.

**Comment by xidedix** [comment]
see also #288

**Comment by carxl** [comment]
@xidedix Thanks for ur answer :) To fix it, i added in table tag:

`<table class="table-responsive">`

**Comment by sebastian-raubach** [comment]
I'm still seeing this issue on these versions:
```
"@coreui/coreui": "^2.1.16",
"@coreui/vue": "^2.1.2",
```
It's definitely the table header that's causing the issue for me, because when I delete it using the dev console, the page width goes down to what I'd expect.

![2020-01-29 16_05_48-DevTools - ics hutton ac uk_germinate-demo-4_#_data_germplasm](https://user-images.githubusercontent.com/12698452/73374044-7d79cb80-42b1-11ea-9c10-ea62a84414a9.png)
