### ISSUE TITLE
Why do you copy Bootstrap Scss into the repo?

### ISSUE THREAD

**Issue by drmonkeyninja** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#51]
Why are you copying the Bootstrap files into the CoreUI repository rather than including the files directly from `bower_components`? Using `bower_components` directly would surely make it easier to maintain CoreUI and update Bootstrap? You could then gitignore the `bower_components` directory to remove repo bloat so that for example you don't need to keep a copy of the entire Bootstrap Sass library within your own code. As far as I can see you're not taking full advantage of using Bower.

**Comment by mrholek** [comment]
1. I don't use bower in Angular 2 Version,
2. I don't use bootstrap.scss file, all files are included in style.scss
3. I use custom variables
4. I don't use all bootstrap components, ex. jumbotron, because no one use jumbotron in admin panel.

**Comment by drmonkeyninja** [comment]
Thanks @mrholek. so does this mean that you customise the actual Bootstrap files once you've copied them to the repository?

Also, I'm looking into incorporating CoreUI with my base framework for a CMS. What is the best way of installing CoreUI so that it can be easily updated as you release new versions? Normally I'd make use of Bower for this, but this doesn't appear to be an option with your theme. Sorry if this is a stupid question, but it didn't seem clear from the docs. Typically there'd be a fair amount of custom JS and some CSS required by the CMS I'm working with on top of what will hopefully be CoreUI.

**Comment by DeeJaVu** [comment]
@mrholek then theres no way we will use this unorganized shit

**Comment by christopher-s** [comment]
I'd like to jump in and leave my two cents.

I use Bootstrap in many projects and do not pull it into my repository like is being done here.

I use NPM to include Bootstrap SASS as a dependency and then only pull in the SCSS files that I require from Bootstrap (instead of including them all). There's no reason that can't be done here - just pull in bootstrap as a package.json dependency.

Overall, the Core UI is fairly impressive, but I'm worried that core Bootstrap SCSS files may get modified - making upgrades difficult.
