### ISSUE TITLE
[(ngModel)]  isn't a known property of 'input'. 

### ISSUE THREAD

**Issue by NewVisualKey** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#93]
**Node:**
npm -v 4.1.1
**ng:**
angular-cli: 1.0.0-beta.26
node: 6.7.0
os: win32 x64
@angular/common: 2.4.4
@angular/compiler: 2.4.4
@angular/core: 2.4.4
@angular/forms: 2.4.4
@angular/http: 2.4.4
@angular/platform-browser: 2.4.4
@angular/platform-browser-dynamic: 2.4.4
@angular/router: 3.4.4
@angular/upgrade: 2.4.4

I did a test on "Angular2_CLI_Starter"  I edit inside 'dashboard.component.html' and insert this:

    <input [(ngModel)]="username">
        <p>Hello {{username}}!</p>

also 'app.modules' I've imported  

import { FormsModule } from '@angular/forms';

and added FormsModule  into the @NgModule 

http://puu.sh/tv1K8.png

**Comment by utpal-patel** [comment]
@NewVisualKey did you find any solutions?

I have tried reactive way...i still get same.

http://prntscr.com/e8limg

**Comment by thanushcst** [comment]
Still have Can't bind to 'ngModel' problem. Even, import the `import { FormsModule } from '@angular/forms'; ` any solution?

**Comment by thanushcst** [comment]
Move the 
import FormsModule  to **pages.module** It will work.

**Comment by utpal-patel** [comment]
Thanks for your reply!!

It worked.

**Comment by mosdeveloper** [comment]
Hi how was this resolved? It says 'thanks for your reply!! It worked." Could you please share your solution? Thanks!

**Comment by JakubR** [comment]
Hi, I also have problem with [(ngModel)]
ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'input'. ("ated fadeIn">
  <a [routerLink]="link">Abc</a>
  <input type="text" class="form-control" id="login" [ERROR ->][(ngModel)]="model.userName"  value="">
</div>"): ng:///DashboardModule/DashboardComponent.html@2:53
Error: Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'input'. ("ated fadeIn">
  <a [routerLink]="link">Abc</a>
  <input type="text" class="form-control" id="login" [ERROR ->][(ngModel)]="model.userName"  value="">
</div>"): ng:///DashboardModule/DashboardComponent.html@2:53

my app.modules.ts contains :

@NgModule({
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    AppRoutingModule,
    BsDropdownModule.forRoot(),
    TabsModule.forRoot(),
    ChartsModule,
    TranslateModule.forRoot(),
    FormsModule,

I use Angular5_CLI_Starter with version 1.0.8.
Please help :)

**Comment by San-Zer0-786** [comment]
I am getting same problem. What was the solution?

**Comment by San-Zer0-786** [comment]
@utpal-patel 

What was the solution to this? Looks like comment with solution was deleted
